name: 🚀 Automation Deployment in Dev Server

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Local Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ vars.REGISTRY_URL }}/${{ vars.REPO_NAME }}:latest

  deploy:
    needs: [build-and-push-images]
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Local Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Generate .env file
        run: |
          echo "${{ secrets.APP_ENV }}" | base64 --decode > .env
      - name: compose docker down
        run: docker compose down --rmi all --volumes --remove-orphans
      - name: compose docker
        run: docker compose up --pull always -d
